### ISSUE TITLE
Secure web traffic

### ISSUE THREAD

**Issue by johnbradley** [matthewhirschey/ddh.org#33]
Currently www.datadrivenhypothesis.org is only accessible via http.

**Comment by matthewhirschey** [comment]
from: domains.google.com

**Getting an SSL certificate from a Certificate Authority (CA)**
You can obtain an SSL certificate for your domain directly from a CA. You will then have to configure the certificate on your web host or on your own servers if hosting it yourself. 

You can get a free SSL certificate from Let’s Encrypt, a popular CA that provides certificates in the interest of creating a safer Internet:

https://letsencrypt.org/

**Comment by matthewhirschey** [comment]
https://servicesblog.redhat.com/2019/03/15/dynamic-ssl-certificates-using-letsencrypt-on-openshift/

**Comment by dleehr** [comment]
The above blog post and a few other resources pointed me toward https://github.com/tnozicka/openshift-acme, which runs an ACME controller in your openshift project to automatically provision/renew certificates on any route with a specific metadata annotation. Easy to install and exactly what I was looking for.

Unfortunately, it's not yet working with ACMEv2 (https://github.com/tnozicka/openshift-acme/pull/92) , and ACMEv1 was turned off by letsencrypt in October 2019 (https://github.com/tnozicka/openshift-acme/issues/104), so this project doesn't work today. I'll see what else is available.

**Comment by dleehr** [comment]
Also, the Duke OKD docs do automate certificates through ACME, but only for *.duke.edu domains:

> The SSL Certificate Automation service in Duke OKD only support *.duke.edu domains. If you have a non-Duke domain, you will need follow the normal procedure for generating and signing certificates.

https://openshift-docs.cloud.duke.edu/user-guide/locksmith-ssl-certificate-automation/

Edit: Since this procedure uses the same route annotations as openshift-acme, the two might conflict. Maybe we just need to buy a certificate.

**Comment by dleehr** [comment]
> Edit: Since this procedure uses the same route annotations as openshift-acme, the two might conflict. Maybe we just need to buy a certificate.

No it wouldn't conflict. The Duke OKD docs walk you through installing the same controller in your OKD project that looks for the annotation. The duke version is configured to provision certs from locksmith (instead of letsencrypt) but if either worked for us, we could use one or the other.

But openshift-acme doesn't do ACMEv2, so that can't do letsencrypt, and locksmith only issues certs for duke.edu, so we can't use that.

**Comment by dleehr** [comment]
@hirscheylab I requested an SSL certificate through OIT (RITM3050828), so you'll probably get emails about the request. We discussed this at our IT team meeting yesterday, and we're going to see if OIT can generate a certificate for the domain. If not, we can help you purchase from a provider (e.g. [namecheap](https://www.namecheap.com/security/ssl-certificates/)).

**Comment by dleehr** [comment]
After discussing, we decided to go with namecheap. I generated CSR and private key. @hirscheylab purchased earlier today and configured ownership validation through DNS. Namecheap issued the cert and it's now installed on the openshift route.
