### ISSUE TITLE
Code Duplication between R Markdown and R scripts

### ISSUE THREAD

**Issue by johnbradley** [matthewhirschey/ddh.org#4]
There is some code duplication between some R Scripts and R Markdown files
- [code/generate_depmap_data.R](https://github.com/hirscheylab/ddh/blob/master/code/generate_depmap_data.R) and [code/depmap_generate.Rmd](https://github.com/hirscheylab/ddh/blob/master/code/depmap_generate.Rmd)
- [code/generate_depmap_stats.R](https://github.com/hirscheylab/ddh/blob/master/code/generate_depmap_stats.R) and [code/depmap_generate_stats.Rmd](https://github.com/hirscheylab/ddh/blob/master/code/depmap_generate_stats.Rmd)
- [code/generate_depmap_tables.R](https://github.com/hirscheylab/ddh/blob/master/code/generate_depmap_tables.R) and [depmap_generate_pathways.Rmd](https://github.com/hirscheylab/ddh/blob/master/code/depmap_generate_pathways.Rmd)
- [code/generate_depmap_pathways.R](https://github.com/hirscheylab/ddh/blob/master/code/generate_depmap_pathways.R) and [depmap_generate_pathways.Rmd](https://github.com/hirscheylab/ddh/blob/master/code/depmap_generate_pathways.Rmd)

The R Scripts above are meant to be easily run to build data for a production environment.
The R Markdown files are exploratory in nature and contain important notes/comments that we wish to preserve. The R Scripts were created based on the R Markdown files.

**Comment by johnbradley** [comment]
One solution @hirscheylab suggested in email is to create stand-alone R scripts that contain functions that can be called from within other R scripts or R markdown documents.

Another possibility is going back to just having the R Markdown files.
The R scripts were introduced for a number of reasons:
- R scripts are easily run from the command line 
- R scripts have less requirements than R Markdown
- To generate data with R Markdown requires creating a PDF which is thrown away
- The desire to only run the slow data generating R Markdown cells once. This was done by adding `eval=FALSE` to the slow data generating blocks. We might be able to use [cache=TRUE](https://yihui.org/knitr/options/#cache) instead.

Thoughts @dleehr and @hirscheylab?

**Comment by matthewhirschey** [comment]
The Rmd has some additional code that is not redundant, so I'd like to keep them. 

But because these R scripts would be useful for generating the raw data, perhaps it'd be best for me to update some of the Rmd code that is redundant? 

Or I can simply "archive" these Rmd documents (i.e. remove them from the repo)? I'd like to preserve them, if possible, to keep a historical record of what I did (and my thinking), but they aren't necessary for generating the data anymore. 

How is something like this usually handled? Production code vs. dev code?

**Comment by dleehr** [comment]
Good points all around. If the Rmd files serve a purpose right now, it makes sense to keep them in the repo, and either adjust them to reference the .R scripts or document that they were used for EDA and aren't the primary process.

If removed, they won't be erased from history - they just wouldn't be in the current version. Deleting the files and committing that deletion would just be another change in the git history. They'd be available in earlier revisions to serve as historical record. A practice I suggest would be to use a [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging). That serves as a human-readable label (e.g. `exploratory-rmd-20191211`) rather than the commit hash da59eee24eb82d653bedeb66f8b745e930fbaf2d

> How is something like this usually handled? Production code vs. dev code?

I typically start early with version control, and commit with the exploratory stuff (like a single script). Later, as I rearrange code into functions and other files, I remove the exploratory stuff. It remains in the history as the starting point, but isn't active.

**Comment by matthewhirschey** [comment]
Seems the simplest solution would be to create a new EDA dir and move these exploratory files there? I still use them (in fact, working on adding a feature to the network graph, so went back to depmap_network.Rmd to use this as a dev environment, and then will take the code that eventually works and put it in app.R, etc.)

So I can document that they are for EDA, and perhaps move them to a new dir to clean up the repo? 

Good solution?

**Comment by dleehr** [comment]
Sounds good to me
